import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          style={{
            border: '3px solid #22c55e',
            padding: 20,
            marginBottom: 20,
            color: '#f9fafb',
            height: '650px',
          }}
        >
          <h1
            style={{
              marginTop: 0,
              color: '#86efac',
            }}
          >
            Platform 영역 (Next.js)
          </h1>

          <p
            style={{
              margin: '4px 0 12px',
              color: '#bbf7d0',
              fontSize: 14,
            }}
          >
            이 영역은 Next.js 기반 플랫폼 애플리케이션입니다. 하위에 Backbone
            레거시 앱을 MFE 형태로 로드합니다.
          </p>

          <div
            style={{
              marginBottom: 16,
              display: 'flex',
              gap: 12,
            }}
          >
            <Link
              href="/"
              style={{
                background: '#14532d',
                color: '#ecfdf5',
                border: '1px solid #22c55e',
                padding: '6px 12px',
                textDecoration: 'none',
                fontWeight: 'bold',
              }}
            >
              Platform Home (Next Link)
            </Link>

            <Link
              href="/legacy"
              style={{
                background: '#14532d',
                color: '#ecfdf5',
                border: '1px solid #22c55e',
                padding: '6px 12px',
                textDecoration: 'none',
                fontWeight: 'bold',
              }}
            >
              Legacy Main (Next Link)
            </Link>

            <Link
              href="/legacy/detail"
              style={{
                background: '#14532d',
                color: '#ecfdf5',
                border: '1px solid #22c55e',
                padding: '6px 12px',
                textDecoration: 'none',
                fontWeight: 'bold',
              }}
            >
              Legacy Detail(Next Link)
            </Link>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
